language: node_js
node_js:
  - "8"
cache:
  npm: true

install:
  - npm install

script: echo skipping tests

before_deploy: "ng build --prod"
deploy:
  provider: s3
  acl: public_read
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: "nickcacace.com"
  skip_cleanup: true
  local_dir: dist
  on:
    branch: master
