name: CI
on:
  pull_request:
    branches: main
  push:
    branches: main
jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: env
      - run: ls -al /opt/hostedtoolcache
      - run: ls -alR /opt/hostedtoolcache/node
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
      - name: Install Dependencies
        run: npm ci
      - name: Test
        run: npm test
      - name: Build
        run: npm run build
      - name: Deploy
        if: ${{ github.ref_name == 'main' }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          # Only push the latest commit to the gh-pages branch
          # Reduces the size of the repository by not retaining history for generated files
          force_orphan: true
